name: update folder tree

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # 매주 월요일 00:00 실행

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Replace tree block in README.md
        run: |
          START="<!--TREE START-->"
          END="<!--TREE END-->"
      
          TREE_FILE="README_TREE.md"
          echo "## 📁 Folder Structure" > $TREE_FILE
      
          TMP_PRINTED_DIRS=".printed_dirs.tmp"
          > $TMP_PRINTED_DIRS
      
          find . -type f -name "*.md" \
          | grep -vE '^\.\/(\.git|\.github|FOLDER_TREE\.md|README_TREE\.md)$' \
          | sort \
          | while read -r filepath; do
            rel_path="${filepath#./}"
            IFS='/' read -ra parts <<< "$rel_path"
            indent=""
            path_accum=""
      
            for ((i=0; i<${#parts[@]}-1; i++)); do
              part="${parts[$i]}"
              path_accum="${path_accum}/${part}"
              key="${path_accum#/}"
      
              if ! grep -Fxq "$key" "$TMP_PRINTED_DIRS"; then
                echo "${indent}- ${part}/" >> $TREE_FILE
                echo "$key" >> "$TMP_PRINTED_DIRS"
              fi
              indent="$indent  "
            done
      
            filename="${parts[-1]}"
            link=$(echo "$rel_path" | sed 's| |%20|g')
            echo "${indent}- 📄 [${filename}](${link})" >> $TREE_FILE
          done
      
          awk -v s="$START" -v e="$END" '
            $0 ~ s { print s; system("cat README_TREE.md"); inblock=1; next }
            $0 ~ e { print e; inblock=0; next }
            !inblock { print }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Create dynamic commit/branch title
        id: pr_context
        run: |
          YEAR=$(date +%Y)
          MONTH=$(date +%-m)
          DAY=$(date +%-d)
          FIRST_DAY_WEEKDAY=$(date -d "$YEAR-$MONTH-01" +%u)
          WEEK_NUM=$(( (DAY + FIRST_DAY_WEEKDAY - 1) / 7 + 1 ))
          TITLE="📁 Update folder structure - ${MONTH}월 ${WEEK_NUM}주차"
          BRANCH="update-folder-tree-$(date +'%Y%m%d-%H%M%S')"
          echo "TITLE=$TITLE" >> $GITHUB_OUTPUT
          echo "BRANCH=$BRANCH" >> $GITHUB_OUTPUT
          echo "COMMIT=📁 폴더 구조 업데이트 - ${MONTH}월 ${WEEK_NUM}주차" >> $GITHUB_OUTPUT

      - name: Create branch and push
        run: |
          git checkout -b ${{ steps.pr_context.outputs.BRANCH }}
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md
          git commit -m "${{ steps.pr_context.outputs.COMMIT }}" || echo "❗ 변경된 내용 없음"
          git push -u origin ${{ steps.pr_context.outputs.BRANCH }}
