name: update folder tree

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # 매주 월요일 00:00 실행

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Generate folder tree with links
        run: |
          echo "## 📁 Folder Structure" > FOLDER_TREE.md

          find . -type f -name "*.md" | sort | while read path; do
            # depth 계산
            level=$(echo "$path" | grep -o "/" | wc -l)
            indent=""
            for ((i=1; i<level; i++)); do
              indent="$indent  "
            done

            label=$(basename "$path")
            url=$(echo "$path" | sed 's|^\./||;s| |%20|g')
            echo "${indent}- [${label}](${url})" >> FOLDER_TREE.md
          done

      - name: Replace tree block in README.md
        run: |
          START="<!--Tree Start-->"
          END="<!--Tree End-->"
          awk -v s="$START" -v e="$END" '
            $0 ~ s { print; system("cat FOLDER_TREE.md"); skip=1; next }
            $0 ~ e { skip=0 }
            !skip
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Create dynamic PR title and branch
        id: pr_context
        run: |
          YEAR=$(date +%Y)
          MONTH=$(date +%-m)
          DAY=$(date +%-d)
          FIRST_DAY_WEEKDAY=$(date -d "$YEAR-$MONTH-01" +%u)
          WEEK_NUM=$(( (DAY + FIRST_DAY_WEEKDAY - 1) / 7 + 1 ))
          TITLE="📁 Update folder structure - ${MONTH}월 ${WEEK_NUM}주차"
          BRANCH="update-folder-tree-${YEAR}${MONTH}${DAY}"
          echo "TITLE=$TITLE" >> $GITHUB_OUTPUT
          echo "BRANCH=$BRANCH" >> $GITHUB_OUTPUT
          echo "COMMIT=📁 폴더 구조 업데이트 - ${MONTH}월 ${WEEK_NUM}주차" >> $GITHUB_OUTPUT

      - name: Create branch and push changes
        run: |
          git checkout -b ${{ steps.pr_context.outputs.BRANCH }}
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          echo "🔍 Git diff 시작"
          git diff README.md || echo "⚠️ README.md diff 없음"

          git add README.md
          git commit -m "${{ steps.pr_context.outputs.COMMIT }}" || echo "❗ 변경된 내용이 없어 커밋 생략됨"
          git push -u origin ${{ steps.pr_context.outputs.BRANCH }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.pr_context.outputs.BRANCH }}
          base: main
          title: ${{ steps.pr_context.outputs.TITLE }}
          body: "자동 생성된 폴더 구조를 반영합니다."
          commit-message: ${{ steps.pr_context.outputs.COMMIT }}
          delete-branch: true
          reviewers: |
            limsubinn
            kdozlo
            dalcheonroadhead
          labels: "AUTO-UPDATE 🤖"


