name: update folder tree

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}

      - name: Generate folder tree with markdown links
        run: |
          echo "## 📁 Folder Structure" > FOLDER_TREE.md
          find . -type f -name "*.md" | sort | while read file; do
            dir=$(dirname "$file")
            label=$(echo "$dir" | sed 's|^\./||')
            [ -z "$label" ] && continue

            # 이미 출력한 폴더는 제외
            grep -q "^- \[$label\]" FOLDER_TREE.md && continue

            # 상대 경로 링크 변환
            url=$(echo "$file" | sed 's|^\./||;s| |%20|g')
            echo "- [$label]($url)" >> FOLDER_TREE.md
          done

      - name: Update README.md between markers
        run: |
          START="<!--Tree Start-->"
          END="<!--Tree End-->"
          awk -v s="$START" -v e="$END" '
            $0 ~ s { print; system("cat FOLDER_TREE.md"); skip=1; next }
            $0 ~ e { skip=0 }
            !skip
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Create dynamic PR title and branch
        id: pr_context
        run: |
          YEAR=$(date +%Y)
          MONTH=$(date +%-m)
          DAY=$(date +%-d)
          FIRST_DAY_WEEKDAY=$(date -d "$YEAR-$MONTH-01" +%u)
          WEEK_NUM=$(( (DAY + FIRST_DAY_WEEKDAY - 1) / 7 + 1 ))
          TITLE="📁 Update folder structure - ${MONTH}월 ${WEEK_NUM}주차"
          BRANCH="update-folder-tree-${YEAR}${MONTH}${DAY}"
          echo "TITLE=$TITLE" >> $GITHUB_OUTPUT
          echo "BRANCH=$BRANCH" >> $GITHUB_OUTPUT

      - name: Create update branch and push
        run: |
          git checkout -b ${{ steps.pr_context.outputs.BRANCH }}
          git config user.name "수민의 자동화 요정"
          git config user.email "dalcheonroadhead@users.noreply.github.com"
          git add README.md
          git commit -m "📁 폴더 구조 업데이트"
          git push -u origin ${{ steps.pr_context.outputs.BRANCH }} --force

      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          branch: ${{ steps.pr_context.outputs.BRANCH }}
          base: main
          title: ${{ steps.pr_context.outputs.TITLE }}
          body: "자동 생성된 폴더 구조를 반영합니다. 병합 후 README가 최신 상태로 유지됩니다."
          commit-message: "📁 Auto-update: folder tree"
          delete-branch: false

      - name: Get PR number
        id: pr
        run: |
          PR_NUMBER=$(gh pr list --state open --head ${{ steps.pr_context.outputs.BRANCH }} --json number -q '.[0].number')
          echo "PR_NUMBER=$PR_NUMBER" >> "$GITHUB_OUTPUT"

      - name: Auto-merge PR
        if: steps.pr.outputs.PR_NUMBER != ''
        run: |
          gh pr merge ${{ steps.pr.outputs.PR_NUMBER }} --squash --delete-branch --admin
