name: update folder tree

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # 매주 월요일 00:00 업데이트

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Generate folder tree
        run: |
          echo "## 📁 Folder Structure" > FOLDER_TREE.md
          tree -d -L 2 . >> FOLDER_TREE.md

      - name: Update README.md between markers
        run: |
          START="<!--Tree Start-->"
          END="<!--Tree End-->"
          BEFORE=$(awk "/$START/ {exit} {print}" README.md)
          AFTER=$(awk "/$END/ {found=1} found" README.md | tail -n +2)
          {
            echo "$BEFORE"
            echo "$START"
            echo '```'
            cat FOLDER_TREE.md
            echo '```'
            echo "$END"
            echo "$AFTER"
          } > README.md

      - name: Create dynamic PR title
        id: pr_title
        run: |
          YEAR=$(date +%Y)
          MONTH=$(date +%-m)
          DAY=$(date +%-d)
          FIRST_DAY_WEEKDAY=$(date -d "$YEAR-$MONTH-01" +%u)
          WEEK_NUM=$(( (DAY + FIRST_DAY_WEEKDAY - 1) / 7 + 1 ))
          TITLE="📁 Update folder structure - ${MONTH}월 ${WEEK_NUM}주차"
          echo "TITLE=$TITLE" >> $GITHUB_OUTPUT

      - name: Create update branch and push
        run: |
          git checkout -b update-folder-tree
          git add README.md
          git commit -m "📁 Auto-update: folder tree"
          git push -u origin update-folder-tree --force

      - name: Get PR number
        id: pr
        run: |
          echo "🔍 현재 열린 PR 리스트:"
          gh pr list --state open --head update-folder-tree
          PR_NUMBER=$(gh pr list --state open --head update-folder-tree --json number -q '.[0].number')
          echo "PR_NUMBER=$PR_NUMBER" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
  
      - name: Auto-merge PR
        if: steps.pr.outputs.PR_NUMBER != ''
        run: |
          gh pr merge ${{ steps.pr.outputs.PR_NUMBER }} --squash --delete-branch --admin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
