name: update folder tree

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # 매주 월요일 00:00 실행

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Replace tree block in README.md
        run: |
          START="<!--TREE START-->"
          END="<!--TREE END-->"
          
          # 트리 문자열을 먼저 변수에 담는다 (HEREDOC 사용)
          TREE_CONTENT=$(find . -type f -name "*.md" \
            | grep -vE "^\.\/(\.github|FOLDER_TREE\.md)" \
            | sort \
            | while read -r path; do
                depth=$(echo "$path" | awk -F"/" '{print NF-1}')
                indent=""
                for ((i=1; i<depth; i++)); do
                  indent="$indent  "
                done
                filename=$(basename "$path")
                cleanpath=$(echo "$path" | sed 's|^\./||' | sed 's| |%20|g')
                echo "${indent}- 📄 [${filename}](${cleanpath})"
              done)

          # awk로 README 내용 교체
          awk -v s="$START" -v e="$END" -v tree="$TREE_CONTENT" '
            $0 ~ s { print s; print tree; inblock=1; next }
            $0 ~ e { print e; inblock=0; next }
            !inblock { print }
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Create dynamic commit/branch title
        id: pr_context
        run: |
          YEAR=$(date +%Y)
          MONTH=$(date +%-m)
          DAY=$(date +%-d)
          FIRST_DAY_WEEKDAY=$(date -d "$YEAR-$MONTH-01" +%u)
          WEEK_NUM=$(( (DAY + FIRST_DAY_WEEKDAY - 1) / 7 + 1 ))
          TITLE="📁 Update folder structure - ${MONTH}월 ${WEEK_NUM}주차"
          BRANCH="update-folder-tree-$(date +'%Y%m%d-%H%M%S')"
          echo "TITLE=$TITLE" >> $GITHUB_OUTPUT
          echo "BRANCH=$BRANCH" >> $GITHUB_OUTPUT
          echo "COMMIT=📁 폴더 구조 업데이트 - ${MONTH}월 ${WEEK_NUM}주차" >> $GITHUB_OUTPUT

      - name: Create branch and push
        run: |
          git checkout -b ${{ steps.pr_context.outputs.BRANCH }}
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add README.md
          git commit -m "${{ steps.pr_context.outputs.COMMIT }}" || echo "❗ 변경된 내용 없음"
          git push -u origin ${{ steps.pr_context.outputs.BRANCH }}
